// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// GetMean
Rcpp::NumericVector GetMean(const Rcpp::NumericVector& inputValues, const Rcpp::List& mixtureModels, const double alpha);
RcppExport SEXP _game_GetMean(SEXP inputValuesSEXP, SEXP mixtureModelsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type inputValues(inputValuesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mixtureModels(mixtureModelsSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(GetMean(inputValues, mixtureModels, alpha));
    return rcpp_result_gen;
END_RCPP
}
// GetSquaredDistancesToMean
Rcpp::NumericVector GetSquaredDistancesToMean(const Rcpp::List& mixtureModels, const Rcpp::LogicalVector& subsetValues, const Rcpp::NumericVector& nodeValues, const Rcpp::NumericVector& weightValues);
RcppExport SEXP _game_GetSquaredDistancesToMean(SEXP mixtureModelsSEXP, SEXP subsetValuesSEXP, SEXP nodeValuesSEXP, SEXP weightValuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mixtureModels(mixtureModelsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalVector& >::type subsetValues(subsetValuesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type nodeValues(nodeValuesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type weightValues(weightValuesSEXP);
    rcpp_result_gen = Rcpp::wrap(GetSquaredDistancesToMean(mixtureModels, subsetValues, nodeValues, weightValues));
    return rcpp_result_gen;
END_RCPP
}
// GetSquaredDistanceMatrix
Rcpp::NumericVector GetSquaredDistanceMatrix(const Rcpp::List& inputData, const Rcpp::NumericVector& nodeValues, const Rcpp::NumericVector& weightValues);
RcppExport SEXP _game_GetSquaredDistanceMatrix(SEXP inputDataSEXP, SEXP nodeValuesSEXP, SEXP weightValuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type inputData(inputDataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type nodeValues(nodeValuesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type weightValues(weightValuesSEXP);
    rcpp_result_gen = Rcpp::wrap(GetSquaredDistanceMatrix(inputData, nodeValues, weightValues));
    return rcpp_result_gen;
END_RCPP
}
// GetMeanNormalizationFactor
double GetMeanNormalizationFactor(const Rcpp::List& inputData, const Rcpp::NumericVector& nodeValues, const Rcpp::NumericVector& weightValues);
RcppExport SEXP _game_GetMeanNormalizationFactor(SEXP inputDataSEXP, SEXP nodeValuesSEXP, SEXP weightValuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type inputData(inputDataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type nodeValues(nodeValuesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type weightValues(weightValuesSEXP);
    rcpp_result_gen = Rcpp::wrap(GetMeanNormalizationFactor(inputData, nodeValues, weightValues));
    return rcpp_result_gen;
END_RCPP
}
// GetMeanExpectedValue
double GetMeanExpectedValue(const Rcpp::List& inputData, const Rcpp::NumericVector& nodeValues, const Rcpp::NumericVector& weightValues);
RcppExport SEXP _game_GetMeanExpectedValue(SEXP inputDataSEXP, SEXP nodeValuesSEXP, SEXP weightValuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type inputData(inputDataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type nodeValues(nodeValuesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type weightValues(weightValuesSEXP);
    rcpp_result_gen = Rcpp::wrap(GetMeanExpectedValue(inputData, nodeValues, weightValues));
    return rcpp_result_gen;
END_RCPP
}
// PerformReassignment
Rcpp::List PerformReassignment(const Rcpp::IntegerVector& inputMemberships, const Rcpp::List& inputModels, const Rcpp::IntegerVector& referenceModels, const Rcpp::NumericVector& nodeValues, const Rcpp::NumericVector& weightValues, const double alpha);
RcppExport SEXP _game_PerformReassignment(SEXP inputMembershipsSEXP, SEXP inputModelsSEXP, SEXP referenceModelsSEXP, SEXP nodeValuesSEXP, SEXP weightValuesSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type inputMemberships(inputMembershipsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type inputModels(inputModelsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type referenceModels(referenceModelsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type nodeValues(nodeValuesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type weightValues(weightValuesSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(PerformReassignment(inputMemberships, inputModels, referenceModels, nodeValues, weightValues, alpha));
    return rcpp_result_gen;
END_RCPP
}
// ComputeNewReferences
Rcpp::IntegerVector ComputeNewReferences(const Rcpp::IntegerVector& inputReferences, const Rcpp::List& inputModels, const Rcpp::IntegerVector& membershipVector, const Rcpp::NumericVector& nodeValues, const Rcpp::NumericVector& weightValues);
RcppExport SEXP _game_ComputeNewReferences(SEXP inputReferencesSEXP, SEXP inputModelsSEXP, SEXP membershipVectorSEXP, SEXP nodeValuesSEXP, SEXP weightValuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type inputReferences(inputReferencesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type inputModels(inputModelsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type membershipVector(membershipVectorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type nodeValues(nodeValuesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type weightValues(weightValuesSEXP);
    rcpp_result_gen = Rcpp::wrap(ComputeNewReferences(inputReferences, inputModels, membershipVector, nodeValues, weightValues));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_game_GetMean", (DL_FUNC) &_game_GetMean, 3},
    {"_game_GetSquaredDistancesToMean", (DL_FUNC) &_game_GetSquaredDistancesToMean, 4},
    {"_game_GetSquaredDistanceMatrix", (DL_FUNC) &_game_GetSquaredDistanceMatrix, 3},
    {"_game_GetMeanNormalizationFactor", (DL_FUNC) &_game_GetMeanNormalizationFactor, 3},
    {"_game_GetMeanExpectedValue", (DL_FUNC) &_game_GetMeanExpectedValue, 3},
    {"_game_PerformReassignment", (DL_FUNC) &_game_PerformReassignment, 6},
    {"_game_ComputeNewReferences", (DL_FUNC) &_game_ComputeNewReferences, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_game(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
