# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetMean <- function(inputValues, mixtureModels, alpha = 0.2) {
    .Call('_game_GetMean', PACKAGE = 'game', inputValues, mixtureModels, alpha)
}

GetSquaredDistancesToMean <- function(mixtureModels, subsetValues, nodeValues, weightValues) {
    .Call('_game_GetSquaredDistancesToMean', PACKAGE = 'game', mixtureModels, subsetValues, nodeValues, weightValues)
}

GetSquaredDistanceMatrix <- function(inputData, nodeValues, weightValues) {
    .Call('_game_GetSquaredDistanceMatrix', PACKAGE = 'game', inputData, nodeValues, weightValues)
}

GetMeanNormalizationFactor <- function(inputData, nodeValues, weightValues) {
    .Call('_game_GetMeanNormalizationFactor', PACKAGE = 'game', inputData, nodeValues, weightValues)
}

GetMeanExpectedValue <- function(inputData, nodeValues, weightValues) {
    .Call('_game_GetMeanExpectedValue', PACKAGE = 'game', inputData, nodeValues, weightValues)
}

PerformReassignment <- function(inputMemberships, inputModels, referenceModels, nodeValues, weightValues, alpha = 0.2) {
    .Call('_game_PerformReassignment', PACKAGE = 'game', inputMemberships, inputModels, referenceModels, nodeValues, weightValues, alpha)
}

ComputeNewReferences <- function(inputReferences, inputModels, membershipVector, nodeValues, weightValues) {
    .Call('_game_ComputeNewReferences', PACKAGE = 'game', inputReferences, inputModels, membershipVector, nodeValues, weightValues)
}

