# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetMixtureDensity <- function(inputValues, inputModel, logScale) {
    .Call('_game_GetMixtureDensity', PACKAGE = 'game', inputValues, inputModel, logScale)
}

GetMean <- function(inputValues, mixtureModels, alpha = 0.2) {
    .Call('_game_GetMean', PACKAGE = 'game', inputValues, mixtureModels, alpha)
}

GetSquaredDistancesToMean <- function(inputData, subsetValues, nodeValues, weightValues) {
    .Call('_game_GetSquaredDistancesToMean', PACKAGE = 'game', inputData, subsetValues, nodeValues, weightValues)
}

GetSquaredDistanceMatrix <- function(inputData, nodeValues, weightValues) {
    .Call('_game_GetSquaredDistanceMatrix', PACKAGE = 'game', inputData, nodeValues, weightValues)
}

GetMeanRawMoment <- function(inputData, order, nodeValues, weightValues) {
    .Call('_game_GetMeanRawMoment', PACKAGE = 'game', inputData, order, nodeValues, weightValues)
}

